apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "goserver"
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "williamrldb/hello-go:v7"
          startupProbe:
            httpGet:
              path: "/healthz"
              port: 8000
            periodSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: "/healthz"
              port: 8000
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: 8000
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: "goserver-env"
            - secretRef:
                name: "goserver-secret"
          volumeMounts:
            - name: config
              mountPath: "/go/myfamily"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: "configmap-family"
            items:
              - key: "members"
                path: "family.txt"
