apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "goserver"
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image: "williamrldb/hello-go:v2"
          env:
            - name: "NAME"
              value: "William"
            - name: "AGE"
              value: "36"
